# Deploy Pihole entities

- hosts: "{{ ansible_limit | default(omit) }}"
  become: yes

  tasks:

    - name: stop pihole
      ansible.builtin.command:
        service pihole-FTL stop

    - name: copy files
      copy:
        src: pihole/{{ item }}
        dest: /etc/pihole
        owner: home
        group: home
      with_items:
        - custom.list
        - pihole-FTL.conf
        - setupVars.conf
        - dns-servers.conf
        - duckdns.sh
        - pi_rsync.sh

    - name: restart pihole
      ansible.builtin.command:
        service pihole-FTL start

    - name: reload lists
      ansible.builtin.command:
        pihole restartdns reload-lists

    - name: update gravity
      ansible.builtin.command:
        pihole updateGravity