---
title: "Home Dashboard"
subtitle: "M & B's Apps & Tools"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Knowledge Base"
        logo: "assets/tools/wordpress.png"
        subtitle: "M & B's Knowldge Base"
        tag: "app"
        keywords: "wiki knowledge base"
        url: "https://home.local/wordpress/"
        target: "_blank"

      - name: "Pi-Hole DNS (Primary)"
        logo: "assets/tools/pihole.png"
        subtitle: "Network Wide Ad-block"
        tag: "app"
        keywords: "self hosted DNS"
        url: "https://pihole.local/admin/"
        target: "_blank"

      - name: "Pi-Hole DNS (Control)"
        logo: "assets/tools/pihole.png"
        subtitle: "Network Wide Ad-block"
        tag: "app"
        keywords: "self hosted DNS"
        url: "https://home.local/admin/"
        target: "_blank"

      - name: "QNAP NAS"
        logo: "assets/tools/qnap.png"
        subtitle: "Network Attached Storage Server"
        tag: "app"
        keywords: "network atached storage"
        url: "https://nas.local/cgi-bin/"
        target: "_blank"

      - name: "Unifi Control Panel"
        logo: "assets/tools/ubiquiti.png"
        subtitle: "Unifi Cloud Key Gen2+ Network Manager"
        tag: "app"
        keywords: "network management tool unifi"
        url: "http://unifi.local/login?redirect=%2F"
        target: "_blank"

  - name: "Tools Downloads"
    icon: "fas fa-cloud"
    items:
      - name: "WiiU Homebrew"
        logo: "assets/tools/homebrew.png"
        subtitle: "WiiU Homebrew Tools"
        tag: "site"
        url: "http://home.local/WiiU/"
        target: "_blank"

      - name: "Emulators"
        logo: "assets/tools/yuzu.png"
        subtitle: "Game Emulation Tools"
        tag: "site"
        url: "https://home.local/GameHacks"
        target: "_blank"

      - name: "ISO Images"
        logo: "assets/tools/iso.png"
        subtitle: "CD-ROM Images"
        tag: "site"
        url: "https://home.local/ISO-Images"
        target: "_blank"

      - name: "Microsoft Platform Roms"
        logo: "assets/tools/xbox.png"
        subtitle: "Microsoft Roms"
        tag: "site"
        url: "https://r-roms.github.io/megathread/microsoft/"
        target: "_blank"

      - name: "Nintendo Platform Roms"
        logo: "assets/tools/nintendo-nes-1.png"
        subtitle: "Nintendo Roms"
        tag: "site"
        url: "https://r-roms.github.io/megathread/nintendo/"
        target: "_blank"

      - name: "Rddit /r/Roms"
        logo: "assets/tools/memory-rom.png"
        subtitle: "Reddit /r/Roms"
        tag: "site"
        url: "https://www.reddit.com/r/Roms/"
        target: "_blank"

  - name: "Work Network"
    icon: "fas fa-cloud"
    items:
      - name: "Pi-Hole DNS (3c3c1dPVT)"
        logo: "assets/tools/pihole.png"
        subtitle: "Network Wide Ad-block"
        tag: "app"
        keywords: "self hosted DNS"
        url: "http://pvtpihole.local/admin/"
        target: "_blank"

      - name: "Unifi Control Panel (3c3c1dPVT)"
        logo: "assets/tools/ubiquiti.png"
        subtitle: "Unifi Cloud Key Gen2+ Network Manager"
        tag: "app"
        keywords: "network management tool unifi"
        url: "http://pvtunifi.local/login?redirect=%2F"
        target: "_blank"
        
      - name: "Edgerouter EdgeMAX (3c3c1dPVT)"
        logo: "assets/tools/ubiquiti.png"
        subtitle: "EdgeMAX Network Manager"
        tag: "app"
        keywords: "network management tool unifi"
        url: "http://3c3c1dpvt.local"
        target: "_blank"

      - name: "Pingdom Outage Maps"
        logo: "assets/tools/solarwinds-icon.png"
        subtitle: "Pingdom Outage Maps"
        tag: "site"
        keywords: "network check tools"
        url: "https://www.pingdom.com/outages/"
        target: "_blank"