<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.0 setup script
 * Date: Thu, 08 Sep 2022 05:25:57 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: MariaDB 10 Qnap [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'MariaDB 10';
$cfg['Servers'][$i]['host'] = '192.168.184.51';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'phpmyadmin';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'i;AD$gD=v6d.M^G|X4m5D^CyqQea$-.v';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';


